/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as PublicAuthResetpwdRouteImport } from './routes/_public/auth/resetpwd'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthOtpRouteImport } from './routes/_public/auth/otp'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthForgotpwdRouteImport } from './routes/_public/auth/forgotpwd'
import { Route as AuthenticatedDashboardUsersIndexRouteImport } from './routes/_authenticated/dashboard/users/index'
import { Route as AuthenticatedDashboardRoleIndexRouteImport } from './routes/_authenticated/dashboard/role/index'
import { Route as AuthenticatedDashboardProfileIndexRouteImport } from './routes/_authenticated/dashboard/profile/index'
import { Route as AuthenticatedDashboardPermissionIndexRouteImport } from './routes/_authenticated/dashboard/permission/index'
import { Route as AuthenticatedDashboardNotificationsIndexRouteImport } from './routes/_authenticated/dashboard/notifications/index'
import { Route as AuthenticatedDashboardContactIndexRouteImport } from './routes/_authenticated/dashboard/contact/index'
import { Route as AuthenticatedDashboardCategorieIndexRouteImport } from './routes/_authenticated/dashboard/categorie/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const PublicAuthResetpwdRoute = PublicAuthResetpwdRouteImport.update({
  id: '/resetpwd',
  path: '/resetpwd',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthOtpRoute = PublicAuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthForgotpwdRoute = PublicAuthForgotpwdRouteImport.update({
  id: '/forgotpwd',
  path: '/forgotpwd',
  getParentRoute: () => PublicAuthRoute,
} as any)
const AuthenticatedDashboardUsersIndexRoute =
  AuthenticatedDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRoleIndexRoute =
  AuthenticatedDashboardRoleIndexRouteImport.update({
    id: '/role/',
    path: '/role/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileIndexRoute =
  AuthenticatedDashboardProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPermissionIndexRoute =
  AuthenticatedDashboardPermissionIndexRouteImport.update({
    id: '/permission/',
    path: '/permission/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsIndexRoute =
  AuthenticatedDashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContactIndexRoute =
  AuthenticatedDashboardContactIndexRouteImport.update({
    id: '/contact/',
    path: '/contact/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCategorieIndexRoute =
  AuthenticatedDashboardCategorieIndexRouteImport.update({
    id: '/categorie/',
    path: '/categorie/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth': typeof PublicAuthRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth/forgotpwd': typeof PublicAuthForgotpwdRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/otp': typeof PublicAuthOtpRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/resetpwd': typeof PublicAuthResetpwdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/categorie': typeof AuthenticatedDashboardCategorieIndexRoute
  '/dashboard/contact': typeof AuthenticatedDashboardContactIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/permission': typeof AuthenticatedDashboardPermissionIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
  '/dashboard/role': typeof AuthenticatedDashboardRoleIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof PublicAuthRouteWithChildren
  '/': typeof PublicIndexRoute
  '/auth/forgotpwd': typeof PublicAuthForgotpwdRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/otp': typeof PublicAuthOtpRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/auth/resetpwd': typeof PublicAuthResetpwdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/categorie': typeof AuthenticatedDashboardCategorieIndexRoute
  '/dashboard/contact': typeof AuthenticatedDashboardContactIndexRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/dashboard/permission': typeof AuthenticatedDashboardPermissionIndexRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileIndexRoute
  '/dashboard/role': typeof AuthenticatedDashboardRoleIndexRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_public/auth': typeof PublicAuthRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/auth/forgotpwd': typeof PublicAuthForgotpwdRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/otp': typeof PublicAuthOtpRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/auth/resetpwd': typeof PublicAuthResetpwdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/categorie/': typeof AuthenticatedDashboardCategorieIndexRoute
  '/_authenticated/dashboard/contact/': typeof AuthenticatedDashboardContactIndexRoute
  '/_authenticated/dashboard/notifications/': typeof AuthenticatedDashboardNotificationsIndexRoute
  '/_authenticated/dashboard/permission/': typeof AuthenticatedDashboardPermissionIndexRoute
  '/_authenticated/dashboard/profile/': typeof AuthenticatedDashboardProfileIndexRoute
  '/_authenticated/dashboard/role/': typeof AuthenticatedDashboardRoleIndexRoute
  '/_authenticated/dashboard/users/': typeof AuthenticatedDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/'
    | '/auth/forgotpwd'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/resetpwd'
    | '/dashboard/'
    | '/dashboard/categorie'
    | '/dashboard/contact'
    | '/dashboard/notifications'
    | '/dashboard/permission'
    | '/dashboard/profile'
    | '/dashboard/role'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/auth/forgotpwd'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/resetpwd'
    | '/dashboard'
    | '/dashboard/categorie'
    | '/dashboard/contact'
    | '/dashboard/notifications'
    | '/dashboard/permission'
    | '/dashboard/profile'
    | '/dashboard/role'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_public/auth'
    | '/_public/'
    | '/_public/auth/forgotpwd'
    | '/_public/auth/login'
    | '/_public/auth/otp'
    | '/_public/auth/register'
    | '/_public/auth/resetpwd'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/categorie/'
    | '/_authenticated/dashboard/contact/'
    | '/_authenticated/dashboard/notifications/'
    | '/_authenticated/dashboard/permission/'
    | '/_authenticated/dashboard/profile/'
    | '/_authenticated/dashboard/role/'
    | '/_authenticated/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_public/auth/resetpwd': {
      id: '/_public/auth/resetpwd'
      path: '/resetpwd'
      fullPath: '/auth/resetpwd'
      preLoaderRoute: typeof PublicAuthResetpwdRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/otp': {
      id: '/_public/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof PublicAuthOtpRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auth/forgotpwd': {
      id: '/_public/auth/forgotpwd'
      path: '/forgotpwd'
      fullPath: '/auth/forgotpwd'
      preLoaderRoute: typeof PublicAuthForgotpwdRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_authenticated/dashboard/users/': {
      id: '/_authenticated/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/role/': {
      id: '/_authenticated/dashboard/role/'
      path: '/role'
      fullPath: '/dashboard/role'
      preLoaderRoute: typeof AuthenticatedDashboardRoleIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile/': {
      id: '/_authenticated/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/permission/': {
      id: '/_authenticated/dashboard/permission/'
      path: '/permission'
      fullPath: '/dashboard/permission'
      preLoaderRoute: typeof AuthenticatedDashboardPermissionIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications/': {
      id: '/_authenticated/dashboard/notifications/'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contact/': {
      id: '/_authenticated/dashboard/contact/'
      path: '/contact'
      fullPath: '/dashboard/contact'
      preLoaderRoute: typeof AuthenticatedDashboardContactIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/categorie/': {
      id: '/_authenticated/dashboard/categorie/'
      path: '/categorie'
      fullPath: '/dashboard/categorie'
      preLoaderRoute: typeof AuthenticatedDashboardCategorieIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardCategorieIndexRoute: typeof AuthenticatedDashboardCategorieIndexRoute
  AuthenticatedDashboardContactIndexRoute: typeof AuthenticatedDashboardContactIndexRoute
  AuthenticatedDashboardNotificationsIndexRoute: typeof AuthenticatedDashboardNotificationsIndexRoute
  AuthenticatedDashboardPermissionIndexRoute: typeof AuthenticatedDashboardPermissionIndexRoute
  AuthenticatedDashboardProfileIndexRoute: typeof AuthenticatedDashboardProfileIndexRoute
  AuthenticatedDashboardRoleIndexRoute: typeof AuthenticatedDashboardRoleIndexRoute
  AuthenticatedDashboardUsersIndexRoute: typeof AuthenticatedDashboardUsersIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardCategorieIndexRoute:
      AuthenticatedDashboardCategorieIndexRoute,
    AuthenticatedDashboardContactIndexRoute:
      AuthenticatedDashboardContactIndexRoute,
    AuthenticatedDashboardNotificationsIndexRoute:
      AuthenticatedDashboardNotificationsIndexRoute,
    AuthenticatedDashboardPermissionIndexRoute:
      AuthenticatedDashboardPermissionIndexRoute,
    AuthenticatedDashboardProfileIndexRoute:
      AuthenticatedDashboardProfileIndexRoute,
    AuthenticatedDashboardRoleIndexRoute: AuthenticatedDashboardRoleIndexRoute,
    AuthenticatedDashboardUsersIndexRoute:
      AuthenticatedDashboardUsersIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicAuthRouteChildren {
  PublicAuthForgotpwdRoute: typeof PublicAuthForgotpwdRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthOtpRoute: typeof PublicAuthOtpRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthResetpwdRoute: typeof PublicAuthResetpwdRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthForgotpwdRoute: PublicAuthForgotpwdRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthOtpRoute: PublicAuthOtpRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetpwdRoute: PublicAuthResetpwdRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
